/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.petugas;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Fachri Ul
 */
public class MainPetugas extends javax.swing.JFrame {

    /**
     * Creates new form mainPetugas
     */
    public MainPetugas() {
        initComponents();
        getContentPane().setBackground(new Color(55,55,55));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddDataBuku = new javax.swing.JButton();
        btnDeleteBuku = new javax.swing.JButton();
        btnCreatePeminjaman = new javax.swing.JButton();
        btnViewBuku = new javax.swing.JButton();
        btnCheckStatusBuku = new javax.swing.JButton();
        btnViewAnggota = new javax.swing.JButton();
        btnPengembalianPinjaman = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Petugas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuPetugas.png"))); // NOI18N

        btnAddDataBuku.setBackground(new java.awt.Color(0, 153, 255));
        btnAddDataBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDataBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_to_folder.png"))); // NOI18N
        btnAddDataBuku.setText("Add Data Buku");

        btnDeleteBuku.setBackground(new java.awt.Color(0, 153, 255));
        btnDeleteBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_folder.png"))); // NOI18N
        btnDeleteBuku.setText("Delete Data Buku");
        btnDeleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBukuActionPerformed(evt);
            }
        });

        btnCreatePeminjaman.setBackground(new java.awt.Color(0, 153, 255));
        btnCreatePeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_page.png"))); // NOI18N
        btnCreatePeminjaman.setText("Create Peminjaman");

        btnViewBuku.setBackground(new java.awt.Color(0, 153, 255));
        btnViewBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        btnViewBuku.setText("View List Buku");

        btnCheckStatusBuku.setBackground(new java.awt.Color(0, 153, 255));
        btnCheckStatusBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckStatusBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_accept.png"))); // NOI18N
        btnCheckStatusBuku.setText("Check Status Buku");

        btnViewAnggota.setBackground(new java.awt.Color(0, 153, 255));
        btnViewAnggota.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        btnViewAnggota.setText("View List Anggota");

        btnPengembalianPinjaman.setBackground(new java.awt.Color(0, 153, 255));
        btnPengembalianPinjaman.setForeground(new java.awt.Color(255, 255, 255));
        btnPengembalianPinjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnPengembalianPinjaman.setText("Pengembalian Pinjaman");

        btnBack.setBackground(new java.awt.Color(0, 153, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interface.png"))); // NOI18N
        btnBack.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeleteBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddDataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreatePeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btnViewBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCheckStatusBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPengembalianPinjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDataBuku)
                    .addComponent(btnCheckStatusBuku))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteBuku)
                    .addComponent(btnViewAnggota))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPengembalianPinjaman)
                    .addComponent(btnCreatePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewBuku))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteBukuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDataBuku;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckStatusBuku;
    private javax.swing.JButton btnCreatePeminjaman;
    private javax.swing.JButton btnDeleteBuku;
    private javax.swing.JButton btnPengembalianPinjaman;
    private javax.swing.JButton btnViewAnggota;
    private javax.swing.JButton btnViewBuku;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    //action listener
    public void addListener(ActionListener a){
        btnAddDataBuku.addActionListener(a);
        btnBack.addActionListener(a);
        btnCheckStatusBuku.addActionListener(a);
        btnCreatePeminjaman.addActionListener(a);
        btnDeleteBuku.addActionListener(a);
        btnPengembalianPinjaman.addActionListener(a);
        btnViewAnggota.addActionListener(a);
        btnViewBuku.addActionListener(a);
    }
    
    //gettet button

    public JButton getBtnAddDataBuku() {
        return btnAddDataBuku;
    }

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnCheckStatusBuku() {
        return btnCheckStatusBuku;
    }

    public JButton getBtnCreatePeminjaman() {
        return btnCreatePeminjaman;
    }

    public JButton getBtnDeleteBuku() {
        return btnDeleteBuku;
    }

    public JButton getBtnPengembalianPinjaman() {
        return btnPengembalianPinjaman;
    }

    public JButton getBtnViewAnggota() {
        return btnViewAnggota;
    }

    public JButton getBtnViewBuku() {
        return btnViewBuku;
    }

    
    
}
